### ISSUE TITLE
just a doubt pls

### ISSUE THREAD

**Issue by X3eRo0** [pseyfert/35c3-ctf#1]
i tried coredumpctl for the first time on my linux mint so noob question here.
XXXXXX@XXXXXX-VirtualBox:~$ coredumpctl debug --debugger=my-gdb
coredumpctl: unrecognized option '--debugger=my-gdb'
what to do i.
i also searched on google

**Comment by pseyfert** [comment]
That's (maybe too briefly?) covered in the lines after.

coredumpctl starts by default `gdb` as debugger. And because 99% of my gdb
usage is "dump the stacktrace and quit" I deployed a shortcut on my system:

I have a text file (with execution bit set) named `my-gdb` written myself.

The content of `my-gdb` is

```
#!/bin/sh

exec gdb -q -n -ex 'thread apply all bt' -batch "$@"
```

The file is in `/home/pseyfert/.local/bin/` and my `PATH` variable is

```sh
shellprompt > echo $PATH
/home/pseyfert/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin: ....
```

So a more general / common usage would be to just call `coredumpctl debug`,
land on a gdb prompt and work from there (i.e. use the `bt` command and that's
all I needed for this ctf).

Does that help?

**Comment by x3ero0** [comment]
It helped me.
